using System.Globalization;
using System.Net;
using System.Text;
using StepRecorder.Core.Storage;

namespace StepRecorder.Core.Reporting;

/// <summary>
/// Writes <c>report.html</c> plus <c>assets/report.css</c> and <c>assets/report.js</c>. Every link is
/// relative and nothing loads from the network, so the session folder can be moved, zipped or opened
/// offline. The page also works with JavaScript disabled.
/// </summary>
public sealed class HtmlReportExporter : IReportExporter
{
    public const string AssetsFolderName = "assets";

    public string FileName => "report.html";

    public void Export(ReportModel report, string sessionDirectory)
    {
        string assets = Path.Combine(sessionDirectory, AssetsFolderName);
        Directory.CreateDirectory(assets);
        AtomicFile.WriteAllText(Path.Combine(assets, "report.css"), ReportAssets.Css);
        AtomicFile.WriteAllText(Path.Combine(assets, "report.js"), ReportAssets.Script);
        AtomicFile.WriteAllText(Path.Combine(sessionDirectory, FileName), Render(report));
    }

    public static string Render(ReportModel report)
    {
        var html = new StringBuilder();
        string title = Encode(report.Title);

        html.Append($"""
            <!doctype html>
            <html lang="en">
            <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta name="generator" content="Step Recorder {Encode(report.ApplicationVersion)}">
            <title>{title} — Step Recorder</title>
            <link rel="stylesheet" href="assets/report.css">
            </head>
            <body>
            <header class="report-header">
            <h1>{title}</h1>
            <dl class="meta">
            <div><dt>Started</dt><dd>{Encode(ReportText.DateTime(report.StartedAt))}</dd></div>
            <div><dt>Duration</dt><dd>{Encode(ReportText.Duration(report.Duration))}</dd></div>
            <div><dt>Steps</dt><dd>{report.Steps.Count}</dd></div>
            <div><dt>Status</dt><dd>{Encode(ReportText.Status(report.Status))}</dd></div>
            <div><dt>System</dt><dd>{Encode(report.OperatingSystem)}</dd></div>
            </dl>
            </header>
            <main>

            """);

        if (report.Steps.Count == 0)
        {
            html.Append("<p class=\"empty\">No steps were recorded.</p>\n");
        }
        else
        {
            html.Append("<ol class=\"steps\">\n");
            foreach (ReportStep step in report.Steps)
            {
                AppendStep(html, step);
            }

            html.Append("</ol>\n");
        }

        html.Append($"""
            </main>
            <footer>Generated by Step Recorder {Encode(report.ApplicationVersion)}</footer>
            <script src="assets/report.js"></script>
            </body>
            </html>

            """);
        return html.ToString();
    }

    private static void AppendStep(StringBuilder html, ReportStep step)
    {
        html.Append($"""
            <li class="step" id="step-{step.Number}">
            <article>
            <header>
            <h2><a href="#step-{step.Number}">{Encode(step.Heading)}</a></h2>
            <time datetime="{Encode(step.Timestamp.ToString("O", CultureInfo.InvariantCulture))}">{Encode(ReportText.Time(step.Timestamp))}</time>
            </header>
            <p class="description">{Encode(step.Description)}</p>

            """);

        if (step.Screenshot is { } shot)
        {
            string src = Encode(ReportText.UrlPath(shot.RelativePath));
            html.Append($"""
                <figure class="shot">
                <a href="{src}" class="shot-link">
                <img src="{src}" width="{shot.Width}" height="{shot.Height}" loading="lazy" alt="Screenshot of {Encode(step.WindowTitle ?? step.ApplicationName)} for step {step.Number}">

                """);

            if (shot.Marker is { } marker)
            {
                html.Append($"""
                    <span class="click-marker" style="left: {Percent(marker.LeftPercent)}; top: {Percent(marker.TopPercent)}" role="img" aria-label="Click position ({marker.X}, {marker.Y})"></span>

                    """);
            }

            html.Append("</a>\n</figure>\n");
        }

        if (!string.IsNullOrWhiteSpace(step.ScreenshotNote))
        {
            string label = step.Screenshot is null ? "No screenshot" : "Note";
            html.Append($"<p class=\"shot-note\"><strong>{label}:</strong> {Encode(step.ScreenshotNote)}</p>\n");
        }

        html.Append("</article>\n</li>\n");
    }

    private static string Percent(double value) => value.ToString("0.###", CultureInfo.InvariantCulture) + "%";

    private static string Encode(string? value) => WebUtility.HtmlEncode(value ?? "");
}
