using System.Text;
using StepRecorder.Core.Storage;

namespace StepRecorder.Core.Reporting;

/// <summary>
/// Writes <c>report.md</c>: the same steps as the HTML report, with relative image links. Markdown
/// can't overlay a click marker, so it gives the click position in the text. Marked screenshot copies
/// come in Phase 5.
/// </summary>
public sealed class MarkdownReportExporter : IReportExporter
{
    public string FileName => "report.md";

    public void Export(ReportModel report, string sessionDirectory) =>
        AtomicFile.WriteAllText(Path.Combine(sessionDirectory, FileName), Render(report));

    public static string Render(ReportModel report)
    {
        var md = new StringBuilder();
        md.Append("# ").Append(Escape(report.Title)).Append("\n\n");
        md.Append("- **Started:** ").Append(ReportText.DateTime(report.StartedAt)).Append('\n');
        md.Append("- **Duration:** ").Append(ReportText.Duration(report.Duration)).Append('\n');
        md.Append("- **Steps:** ").Append(report.Steps.Count).Append('\n');
        md.Append("- **Status:** ").Append(Escape(ReportText.Status(report.Status))).Append('\n');
        md.Append("- **System:** ").Append(Escape(report.OperatingSystem)).Append("\n\n");

        if (report.Steps.Count == 0)
        {
            md.Append("No steps were recorded.\n\n");
        }

        foreach (ReportStep step in report.Steps)
        {
            md.Append("## ").Append(Escape(step.Heading)).Append("\n\n");
            md.Append(Escape(step.Description)).Append("  \n");
            md.Append('*').Append(ReportText.Time(step.Timestamp)).Append("*\n\n");

            if (step.Screenshot is { } shot)
            {
                string alt = Escape($"Step {step.Number} screenshot");
                md.Append("![").Append(alt).Append("](").Append(ReportText.UrlPath(shot.RelativePath)).Append(")\n\n");
            }

            if (!string.IsNullOrWhiteSpace(step.ScreenshotNote))
            {
                string label = step.Screenshot is null ? "No screenshot" : "Note";
                md.Append("> **").Append(label).Append(":** ").Append(Escape(step.ScreenshotNote)).Append("\n\n");
            }
        }

        md.Append("---\n\n*Generated by Step Recorder ").Append(Escape(report.ApplicationVersion)).Append("*\n");
        return md.ToString();
    }

    /// <summary>
    /// Backslash-escapes characters Markdown would treat as formatting, so window titles such as
    /// <c>*draft* [1] &lt;b&gt;</c> show literally. Line breaks become spaces to keep structure intact.
    /// </summary>
    public static string Escape(string? text)
    {
        if (string.IsNullOrEmpty(text))
        {
            return "";
        }

        var builder = new StringBuilder(text.Length + 8);
        foreach (char c in text)
        {
            switch (c)
            {
                case '\r' or '\n':
                    builder.Append(' ');
                    break;
                // Enough for inline text: every line we write starts with our own prefix ("## ", "> ",
                // or the description's verb), so line-start markers such as "-" and "1." can't trigger.
                case '\\' or '`' or '*' or '_' or '[' or ']' or '<' or '>' or '#' or '|' or '~':
                    builder.Append('\\').Append(c);
                    break;
                default:
                    builder.Append(c);
                    break;
            }
        }

        return builder.ToString();
    }
}
